---
#For reference:-
#https://cyso.cloud/docs/cloud/extra/how-to-install-wordpress-using-ansible/#step-2-making-it-a-lamp-server
#https://github.com/do-community/ansible-playbooks/tree/master/wordpress-lamp_ubuntu1804

# The Wordpress Deployment With Ansible

- name: Run The Wordpress Project With Ansible
  hosts: wordpress
  become: yes
  vars_files:
  - variables/project-vars
  roles:
  - common
  - mysql
  - php
  - nginx
  - wordpress
