- name: Update system packages "apt" and cache & install common dependencies
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 3600
    name:
    - curl
    - unzip
